<!-- Theme style -->
<link rel="stylesheet" href="http://localhost:3001/dist/css/AdminLTE.min.css">
<link rel="stylesheet" href="http://localhost:3001/dist/css/style.css">
<!-- AdminLTE Skins. Choose a skin from the css/skins
    folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="http://localhost:3001/dist/css/skins/_all-skins.min.css">
<script src="http://localhost:3001/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<script src="http://localhost:3001/bower_components/fastclick/lib/fastclick.js"></script>
<script src="http://localhost:3001/dist/js/adminlte.min.js"></script>
<link rel="stylesheet" href="http://localhost:3001/plugins/iCheck/all.css">
<script src="http://localhost:3001/plugins/iCheck/icheck.min.js"></script>