<!-- Theme style -->
<link rel="stylesheet" href="../../../../dist/css/AdminLTE.min.css">
<link rel="stylesheet" href="../../../../dist/css/style.css">
<!-- AdminLTE Skins. Choose a skin from the css/skins
    folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="../../../../dist/css/skins/_all-skins.min.css">
<script src="../../../../local_modules/fastclick/lib/fastclick.js"></script>
<script src="../../../../dist/js/adminlte.min.js"></script>
<link rel="stylesheet" href="../../../../plugins/iCheck/all.css">
<script src="../../../../plugins/iCheck/icheck.min.js"></script>